server {
    server_name omendapipaysglobel.online www.omendapipaysglobel.online;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }

    location ~* \.(html)$ {
        root /var/www/omenda-pi-pays;
        try_files $uri =404;
    }

    add_header Content-Security-Policy "frame-ancestors 'self' https://app-cdn.minepi.com https://*.minepi.com";
    add_header X-Content-Type-Options "nosniff";

    listen [::]:443 ssl ipv6only=on;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/omendapipaysglobel.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/omendapipaysglobel.online/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
server {
    if ($host = omendapipaysglobel.online) {
        return 301 https://$host$request_uri;
    }
    listen 80;
    listen [::]:80;
    server_name omendapipaysglobel.online www.omendapipaysglobel.online;
    return 404;
}
