import { Hotel, Property, BillProvider } from "./types";

// ============ Mock Hotels ============
export const hotels: Hotel[] = [
  {
    id: "h1",
    name: "Serena Hotel Dar es Salaam",
    location: "Dar es Salaam, Tanzania",
    rating: 4.8,
    pricePerNight: 0.0006,
    image: "https://picsum.photos/seed/serena/600/400",
    amenities: ["WiFi", "Pool", "Spa", "Restaurant", "Gym", "Parking"],
    description: "A 5-star luxury hotel overlooking the Indian Ocean with world-class amenities.",
    rooms: 230,
    type: "luxury",
  },
  {
    id: "h2",
    name: "Hyatt Regency",
    location: "Nairobi, Kenya",
    rating: 4.6,
    pricePerNight: 0.0005,
    image: "https://picsum.photos/seed/hyatt/600/400",
    amenities: ["WiFi", "Pool", "Restaurant", "Gym", "Bar"],
    description: "Modern hotel in the heart of Nairobi with stunning city views.",
    rooms: 186,
    type: "luxury",
  },
  {
    id: "h3",
    name: "Zanzibar Beach Resort",
    location: "Zanzibar, Tanzania",
    rating: 4.9,
    pricePerNight: 0.001,
    image: "https://picsum.photos/seed/zanzibar/600/400",
    amenities: ["WiFi", "Beach", "Pool", "Spa", "Restaurant", "Diving"],
    description: "Beachfront paradise with crystal-clear waters and white sand beaches.",
    rooms: 80,
    type: "luxury",
  },
  {
    id: "h4",
    name: "City Lodge Hotel",
    location: "Kampala, Uganda",
    rating: 4.2,
    pricePerNight: 0.0002,
    image: "https://picsum.photos/seed/citylodge/600/400",
    amenities: ["WiFi", "Restaurant", "Parking", "Laundry"],
    description: "Comfortable mid-range hotel ideal for business travelers.",
    rooms: 120,
    type: "standard",
  },
  {
    id: "h5",
    name: "Mountain View Inn",
    location: "Arusha, Tanzania",
    rating: 4.4,
    pricePerNight: 0.0003,
    image: "https://picsum.photos/seed/mountainview/600/400",
    amenities: ["WiFi", "Restaurant", "Garden", "Tours"],
    description: "Charming inn at the foot of Mount Meru with safari tour packages.",
    rooms: 40,
    type: "standard",
  },
  {
    id: "h6",
    name: "Pioneer Backpackers",
    location: "Mombasa, Kenya",
    rating: 4.0,
    pricePerNight: 0.00008,
    image: "https://picsum.photos/seed/backpack/600/400",
    amenities: ["WiFi", "Kitchen", "Lounge"],
    description: "Budget-friendly hostel near the beach for adventurous pioneers.",
    rooms: 30,
    type: "budget",
  },
];

// ============ Mock Properties ============
export const properties: Property[] = [
  {
    id: "p1",
    title: "Modern Villa with Ocean View",
    location: "Masaki, Dar es Salaam",
    price: 6.5,
    image: "https://picsum.photos/seed/villa1/600/400",
    bedrooms: 5,
    bathrooms: 4,
    area: 320,
    type: "house",
    description: "Stunning modern villa with panoramic ocean views, private pool, and landscaped garden.",
    featured: true,
  },
  {
    id: "p2",
    title: "3BR Apartment in Westlands",
    location: "Westlands, Nairobi",
    price: 1.6,
    image: "https://picsum.photos/seed/apt1/600/400",
    bedrooms: 3,
    bathrooms: 2,
    area: 140,
    type: "apartment",
    description: "Spacious apartment in a secure complex with gym, pool, and 24/7 security.",
    featured: true,
  },
  {
    id: "p3",
    title: "Commercial Plot - CBD",
    location: "CBD, Dar es Salaam",
    price: 15,
    image: "https://picsum.photos/seed/land1/600/400",
    bedrooms: 0,
    bathrooms: 0,
    area: 2000,
    type: "land",
    description: "Prime commercial plot in the central business district, ideal for office development.",
    featured: false,
  },
  {
    id: "p4",
    title: "Penthouse Suite",
    location: "Kilimani, Nairobi",
    price: 4.8,
    image: "https://picsum.photos/seed/pent1/600/400",
    bedrooms: 4,
    bathrooms: 3,
    area: 250,
    type: "apartment",
    description: "Luxury penthouse with rooftop terrace, smart home features, and concierge service.",
    featured: true,
  },
  {
    id: "p5",
    title: "Family Home in Mikocheni",
    location: "Mikocheni, Dar es Salaam",
    price: 2.5,
    image: "https://picsum.photos/seed/house2/600/400",
    bedrooms: 4,
    bathrooms: 3,
    area: 200,
    type: "house",
    description: "Beautiful family home in a quiet neighborhood with large compound and servant quarters.",
    featured: false,
  },
  {
    id: "p6",
    title: "Retail Space - Mall",
    location: "Mlimani City, Dar es Salaam",
    price: 1.3,
    image: "https://picsum.photos/seed/shop1/600/400",
    bedrooms: 0,
    bathrooms: 1,
    area: 80,
    type: "commercial",
    description: "High-traffic retail space in premier shopping mall with excellent foot traffic.",
    featured: false,
  },
];

// ============ Bill Providers ============
export const billProviders: BillProvider[] = [
  { id: "b1", name: "TANESCO", icon: "⚡", category: "electricity", description: "Tanzania Electric Supply Company" },
  { id: "b2", name: "DAWASCO", icon: "💧", category: "water", description: "Dar es Salaam Water & Sewerage" },
  { id: "b3", name: "Vodacom", icon: "📱", category: "phone", description: "Vodacom Tanzania" },
  { id: "b4", name: "Airtel", icon: "📱", category: "phone", description: "Airtel Tanzania" },
  { id: "b5", name: "Tigo/MIC", icon: "📱", category: "phone", description: "MIC Tanzania (Tigo)" },
  { id: "b6", name: "TTCL Fiber", icon: "🌐", category: "internet", description: "TTCL Internet Services" },
  { id: "b7", name: "Raha Fiber", icon: "🌐", category: "internet", description: "Raha ISP Fiber Internet" },
  { id: "b8", name: "DSTV", icon: "📺", category: "tv", description: "MultiChoice DSTV Subscription" },
  { id: "b9", name: "Azam TV", icon: "📺", category: "tv", description: "Azam Media TV Subscription" },
  { id: "b10", name: "Jubilee Insurance", icon: "🛡️", category: "insurance", description: "Jubilee Insurance Premium" },
  { id: "b11", name: "NSSF", icon: "🛡️", category: "insurance", description: "National Social Security Fund" },
  { id: "b12", name: "Kenya Power", icon: "⚡", category: "electricity", description: "Kenya Power & Lighting" },
];
